### ISSUE TITLE
[OwnerManagement] add a parking censor on it, fog lamps, spoiler, automatic driver window, matic transmission

### ISSUE THREAD

**Issue by JeffJrShim** [JeffJrShim/rinku-cogs#6]
https://canary.discord.com/channels/432379300684103699/432380977755586561/902077177871368233

**Comment by JeffJrShim** [comment]
i need a comment so i can forcefully deny it raiden

**Comment by Hajime222** [comment]
Color : Maroon Red, Mugen bodykit, 4 spare tires, and a 12 months warranty

**Comment by JeffJrShim** [comment]
No

**Comment by JeffJrShim** [comment]
this is a joke dw
